scaffold_workspace=/Users/zhanglizhi/workspace/sparrow
scaffold_backend_template_home=
scaffold_frontend_template_home=
scaffold_frontend_home=/Users/zhanglizhi/workspace/sparrow/sparrow-js

scaffold_multi_user=false
resource=http://r.sparrowzoo.net
image_website=sparrowzoo
root_path=http://localhost:7777
sparrow.profile=dev
logback.dir=./logs
sparrow.blog.content-dir=/Users/zhanglizhi/workspace/sparrow/sparrowzoo/content
sparrow.blog.site-url=http://localhost:8888
redis_url=127.0.0.1:6379
redis.pool.maxActive=5
redis.pool.maxIdle=2
upload=http://u.r.sparrowzoo.net
physical_resource=/Users/zhanglizhi/workspace/sparrow/sparrow-js/source
physical_upload=/Users/zhanglizhi/upload
swagger.enable=true
authenticator.encrypt_key=123456
authenticator.validate_device_id=false
authenticator.validate_status=false
authenticator.token_available_days=7
authenticator.remember_me_days=15
authenticator.skip_password_valid=true
authenticator.mock_login_user=true
captcha_service=mock

