scaffold_multi_user=true
resource=https://r.sparrowzoo.net
root_path=https://api.sparrowzoo.com
sparrow.blog.content-dir=/workspace/sparrowzoo/content
sparrow.blog.site-url=http://blog.sparrowzoo.com
image_website=sparrowzoo
sparrow.profile=prod
logback.dir=/var/log/sparrowzoo
auth.encrypt_key=123456
redis_url=127.0.0.1:6379
redis.pool.maxActive=5
redis.pool.maxIdle=2
upload=https://u.r.sparrowzoo.net
physical_resource=/workspace/sparrow-js/source
physical_upload=/workspace/upload
swagger.enable=true
authenticator.encrypt_key=wwr289624@#6824
authenticator.validate_device_id=true
authenticator.validate_status=true
authenticator.token_available_days=7
authenticator.login_token_available_days=1
authenticator.remember_me_days=15
authenticator.skip_password_valid=false
authenticator.mock_login_user=false



