<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>infra-bom</artifactId>
        <groupId>com.sparrowzoo</groupId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath/>
    </parent>
    <packaging>pom</packaging>
    <artifactId>security-bom</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <groupId>com.sparrowzoo.security</groupId>
    <properties>
        <security_version>1.0.0-SNAPSHOT</security_version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.sparrowzoo.security.admin</groupId>
                <artifactId>security-admin-protocol</artifactId>
                <version>${security_version}</version>
            </dependency>
            <dependency>
                <groupId>com.sparrowzoo.security.admin</groupId>
                <artifactId>security-admin-dao-api</artifactId>
                <version>${security_version}</version>
            </dependency>

            <dependency>
                <groupId>com.sparrowzoo.security.admin</groupId>
                <artifactId>security-admin-dao-sparrow</artifactId>
                <version>${security_version}</version>
            </dependency>

            <dependency>
                <groupId>com.sparrowzoo.security.admin</groupId>
                <artifactId>security-admin-mybatis</artifactId>
                <version>${security_version}</version>

            </dependency>

            <dependency>
                <groupId>com.sparrowzoo.security.admin</groupId>
                <artifactId>security-admin-infrastructure</artifactId>
                <version>${security_version}</version>

            </dependency>

            <dependency>
                <groupId>com.sparrowzoo.security.admin</groupId>
                <artifactId>security-admin-domain</artifactId>
                <version>${security_version}</version>

            </dependency>
            <dependency>
                <groupId>com.sparrowzoo.security.admin</groupId>
                <artifactId>security-admin-adapter</artifactId>
                <version>${security_version}</version>

            </dependency>
            <dependency>
                <groupId>com.sparrowzoo.security.admin</groupId>
                <artifactId>security-admin-main-spring-boot</artifactId>
                <version>${security_version}</version>
            </dependency>
            <dependency>
                <groupId>com.sparrowzoo.security</groupId>
                <artifactId>security-po</artifactId>
                <version>${security_version}</version>
            </dependency>


            <dependency>
                <groupId>com.sparrowzoo.security</groupId>
                <artifactId>security-protocol</artifactId>
                <version>${security_version}</version>
            </dependency>
            <dependency>
                <groupId>com.sparrowzoo.security</groupId>
                <artifactId>security-dao-api</artifactId>
                <version>${security_version}</version>
            </dependency>

            <dependency>
                <groupId>com.sparrowzoo.security</groupId>
                <artifactId>security-sparrow-dao</artifactId>
                <version>${security_version}</version>
            </dependency>

            <dependency>
                <groupId>com.sparrowzoo.security</groupId>
                <artifactId>security-mybatis</artifactId>
                <version>${security_version}</version>

            </dependency>

            <dependency>
                <groupId>com.sparrowzoo.security</groupId>
                <artifactId>security-infrastructure</artifactId>
                <version>${security_version}</version>

            </dependency>

            <dependency>
                <groupId>com.sparrowzoo.security</groupId>
                <artifactId>security-domain</artifactId>
                <version>${security_version}</version>

            </dependency>
            <dependency>
                <groupId>com.sparrowzoo.security</groupId>
                <artifactId>security-adapter</artifactId>
                <version>${security_version}</version>
            </dependency>
            <dependency>
                <groupId>com.sparrowzoo.security</groupId>
                <artifactId>security-api</artifactId>
                <version>${security_version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
